import java.awt.*;
import java.util.ArrayList;;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author russe
 */
public class ViewTeamMembers extends javax.swing.JFrame {
    DbAccess dataAccess = new DbAccess();
    int projIdGlobal = 0;
    private javax.swing.JScrollPane scroll;
    
    /**
     * Creates new form ViewTeamMembers
     * @param projIdIn
     */
    public ViewTeamMembers(int projIdIn) {
        projIdGlobal = projIdIn;
        initComponents();
        getContentPane().setBackground(new Color(54, 69, 79));
        //begin header
        TextProjId.setText(Integer.toString(projIdIn)); 
        TextTotalExpended.setText(Double.toString(dataAccess.calcExpendedTotal(projIdIn)));            
        TextProjectedHrs.setText(Double.toString(dataAccess.calcProjEstimateTotal(projIdIn)));        
        int qtyRisksOutstanding = 0;        
        ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdIn);
        for(int i = 0; i <= risks.size() -1; i++){
            if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                TextRiskStatus.setText("remaining");
                qtyRisksOutstanding += 1;
            }
        }
        TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
        //End Header
        //Begin Table
        tableTeamMembers.scrollBarUpdateTeamMembersTable(jScrollPane1);   
        DefaultTableModel modelTeamMembersTbl = (DefaultTableModel)tableTeamMembers.getModel();
        ArrayList<ModelTeamMember> resultsList = dataAccess.GetTeamMembers(projIdIn);
        for (int i = 0; i <= resultsList.size() -1; i++) {
                modelTeamMembersTbl.addRow(new Object[]{resultsList.get(i).memberId, resultsList.get(i).memberFirstName, resultsList.get(i).memberLastName, resultsList.get(i).memberPrimaryRole});
        }
        //End Table      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        projectFuncBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        projectFuncBtnHome = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        LabelTotalExpended4 = new javax.swing.JLabel();
        TextProjId = new javax.swing.JLabel();
        LabelTotalExpended3 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JLabel();
        LabelTotalExpended2 = new javax.swing.JLabel();
        TextRiskStatus = new javax.swing.JLabel();
        LabelTotalExpended1 = new javax.swing.JLabel();
        TextProjectedHrs = new javax.swing.JLabel();
        LabelTotalExpended = new javax.swing.JLabel();
        TextTotalExpended = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTotalExpended6 = new javax.swing.JLabel();
        TextLastName = new javax.swing.JTextField();
        LabelTotalExpended7 = new javax.swing.JLabel();
        LabelTotalExpended8 = new javax.swing.JLabel();
        TextFirstName = new javax.swing.JTextField();
        teamMembersFuncBtnReset = new javax.swing.JButton();
        teamMembersFuncBtnAddUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxRole = new ComboBox();
        TextMemberId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        teamMembersFuncBtnDeleteMember = new javax.swing.JButton();
        teamMembersFuncBtnEditMemeber = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTeamMembers = new TableTeamMembers();
        jLabel5 = new javax.swing.JLabel();

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        projectFuncBtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnBack.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnBack.setText("Back");
        projectFuncBtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmt_logo_smaill.jpg"))); // NOI18N
        jLabel1.setAlignmentY(1.0F);

        projectFuncBtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnHome.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnHome.setText("Home");
        projectFuncBtnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnHomeActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        LabelTotalExpended4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended4.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended4.setText("Proj. Id");
        LabelTotalExpended4.setToolTipText("");
        LabelTotalExpended4.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended4.setName(""); // NOI18N
        LabelTotalExpended4.setPreferredSize(new java.awt.Dimension(100, 25));

        TextProjId.setForeground(new java.awt.Color(204, 204, 204));
        TextProjId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjId.setText("0");
        TextProjId.setToolTipText("");
        TextProjId.setMinimumSize(new java.awt.Dimension(100, 25));
        TextProjId.setName(""); // NOI18N
        TextProjId.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended3.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended3.setText("Proj. Status");
        LabelTotalExpended3.setToolTipText("");
        LabelTotalExpended3.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended3.setName(""); // NOI18N
        LabelTotalExpended3.setPreferredSize(new java.awt.Dimension(100, 25));

        TextStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextStatus.setText("In-Process");
        TextStatus.setToolTipText("");
        TextStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextStatus.setName(""); // NOI18N
        TextStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended2.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended2.setText("Risks Status");
        LabelTotalExpended2.setToolTipText("");
        LabelTotalExpended2.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended2.setName(""); // NOI18N
        LabelTotalExpended2.setPreferredSize(new java.awt.Dimension(100, 25));

        TextRiskStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextRiskStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskStatus.setText("Risks Resolved");
        TextRiskStatus.setToolTipText("");
        TextRiskStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextRiskStatus.setName(""); // NOI18N
        TextRiskStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended1.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended1.setText("Projected Hours");
        LabelTotalExpended1.setToolTipText("");
        LabelTotalExpended1.setName(""); // NOI18N
        LabelTotalExpended1.setPreferredSize(new java.awt.Dimension(130, 25));

        TextProjectedHrs.setForeground(new java.awt.Color(204, 204, 204));
        TextProjectedHrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjectedHrs.setText("0");
        TextProjectedHrs.setToolTipText("");
        TextProjectedHrs.setName(""); // NOI18N
        TextProjectedHrs.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended.setText("Expended Hours");
        LabelTotalExpended.setToolTipText("");
        LabelTotalExpended.setName(""); // NOI18N
        LabelTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        TextTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        TextTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTotalExpended.setText("0");
        TextTotalExpended.setToolTipText("");
        TextTotalExpended.setName(""); // NOI18N
        TextTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Project Team Members");
        jLabel3.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        LabelTotalExpended6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended6.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended6.setText("Role:");
        LabelTotalExpended6.setToolTipText("");
        LabelTotalExpended6.setName(""); // NOI18N
        LabelTotalExpended6.setPreferredSize(new java.awt.Dimension(130, 25));

        TextLastName.setForeground(new java.awt.Color(51, 51, 51));
        TextLastName.setText("Enter last name...");
        TextLastName.setToolTipText("");
        TextLastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        TextLastName.setMinimumSize(new java.awt.Dimension(64, 34));
        TextLastName.setName(""); // NOI18N
        TextLastName.setPreferredSize(new java.awt.Dimension(104, 34));
        TextLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextLastNameFocusLost(evt);
            }
        });
        TextLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLastNameActionPerformed(evt);
            }
        });

        LabelTotalExpended7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended7.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended7.setText(" Last Name:");
        LabelTotalExpended7.setToolTipText("");
        LabelTotalExpended7.setName(""); // NOI18N
        LabelTotalExpended7.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended8.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended8.setText("First Name:");
        LabelTotalExpended8.setToolTipText("");
        LabelTotalExpended8.setName(""); // NOI18N
        LabelTotalExpended8.setPreferredSize(new java.awt.Dimension(130, 25));

        TextFirstName.setForeground(new java.awt.Color(51, 51, 51));
        TextFirstName.setText("Enter first name...");
        TextFirstName.setToolTipText("");
        TextFirstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        TextFirstName.setMinimumSize(new java.awt.Dimension(64, 34));
        TextFirstName.setName(""); // NOI18N
        TextFirstName.setPreferredSize(new java.awt.Dimension(106, 34));
        TextFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFirstNameFocusLost(evt);
            }
        });
        TextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFirstNameActionPerformed(evt);
            }
        });

        teamMembersFuncBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamMembersFuncBtnReset.setForeground(new java.awt.Color(0, 51, 102));
        teamMembersFuncBtnReset.setText("Reset");
        teamMembersFuncBtnReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teamMembersFuncBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMembersFuncBtnResetActionPerformed(evt);
            }
        });

        teamMembersFuncBtnAddUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamMembersFuncBtnAddUpdate.setForeground(new java.awt.Color(0, 51, 102));
        teamMembersFuncBtnAddUpdate.setText("Add/Update");
        teamMembersFuncBtnAddUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teamMembersFuncBtnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMembersFuncBtnAddUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add/Edit Stakeholder");

        ComboBoxRole.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Role...", "Owner", "Project Manager", "Product Expert", "Cust. Manager", "Requirements Engineer", "Systems Architecture", "Database Designer", "UI Designer", "Interaction Engineer", "Developer", "Quality Assurance" }));
        ComboBoxRole.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxRole.setPreferredSize(new java.awt.Dimension(163, 33));
        ComboBoxRole.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboBoxRoleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBoxRoleFocusLost(evt);
            }
        });
        ComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRoleActionPerformed(evt);
            }
        });

        TextMemberId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextMemberId.setForeground(new java.awt.Color(0, 51, 102));
        TextMemberId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMemberId.setText("Id: New-Member");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TextMemberId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(teamMembersFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teamMembersFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamMembersFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamMembersFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setToolTipText("");

        teamMembersFuncBtnDeleteMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamMembersFuncBtnDeleteMember.setForeground(new java.awt.Color(204, 0, 0));
        teamMembersFuncBtnDeleteMember.setText("Delete");
        teamMembersFuncBtnDeleteMember.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teamMembersFuncBtnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMembersFuncBtnDeleteMemberActionPerformed(evt);
            }
        });

        teamMembersFuncBtnEditMemeber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamMembersFuncBtnEditMemeber.setForeground(new java.awt.Color(0, 51, 102));
        teamMembersFuncBtnEditMemeber.setText("Edit");
        teamMembersFuncBtnEditMemeber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        teamMembersFuncBtnEditMemeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamMembersFuncBtnEditMemeberActionPerformed(evt);
            }
        });

        tableTeamMembers.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.lightGray)));
        tableTeamMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id.", "First Name", "Last Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTeamMembers);
        if (tableTeamMembers.getColumnModel().getColumnCount() > 0) {
            tableTeamMembers.getColumnModel().getColumn(0).setMinWidth(25);
            tableTeamMembers.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableTeamMembers.getColumnModel().getColumn(1).setMinWidth(25);
            tableTeamMembers.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableTeamMembers.getColumnModel().getColumn(2).setMinWidth(25);
            tableTeamMembers.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableTeamMembers.getColumnModel().getColumn(3).setMinWidth(25);
            tableTeamMembers.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Stakeholder List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(teamMembersFuncBtnEditMemeber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teamMembersFuncBtnDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamMembersFuncBtnEditMemeber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamMembersFuncBtnDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextProjId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextRiskStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextProjectedHrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTotalExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(jSeparator5))
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextProjectedHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextRiskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectFuncBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnBackActionPerformed
        ViewProjectDetails vpd = new ViewProjectDetails(projIdGlobal);
        vpd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnBackActionPerformed

    private void projectFuncBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnHomeActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_projectFuncBtnHomeActionPerformed

    private void teamMembersFuncBtnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMembersFuncBtnAddUpdateActionPerformed
        System.out.println("Add/Update Function");
                String buttonInitialState = ComboBoxRole.getSelectedItem().toString();
        if(buttonInitialState.equalsIgnoreCase("Select Role...")){
            //do nothing maybe display error
        } else{
            DefaultTableModel modelTeamMembersTbl = (DefaultTableModel)tableTeamMembers.getModel();
            ModelTeamMember transitionalMember = new ModelTeamMember();
            if(TextMemberId.getText().equalsIgnoreCase("Id: New-Member")){  
               //new member - add
                transitionalMember.memberId = 0;
                transitionalMember.projNumber = projIdGlobal;
                transitionalMember.memberFirstName= TextFirstName.getText();
                transitionalMember.memberLastName = TextLastName.getText();
                transitionalMember.memberPrimaryRole = ComboBoxRole.getSelectedItem().toString();
                if(transitionalMember.memberFirstName.equalsIgnoreCase("Enter first name...") || transitionalMember.memberFirstName.equalsIgnoreCase("Enter last name...") || transitionalMember.memberFirstName.equalsIgnoreCase("Select Role...")){
                    //do nothing except send a all information required message to the user.
                } else{
                    dataAccess.InsertTeamMember(transitionalMember);
                    ArrayList<ModelTeamMember> resultsList = dataAccess.GetTeamMembers(projIdGlobal);
                    modelTeamMembersTbl.setNumRows(0);
                    for (int i = 0; i <= resultsList.size() -1; i++) {
                        modelTeamMembersTbl.addRow(new Object[]{resultsList.get(i).memberId, resultsList.get(i).memberFirstName, resultsList.get(i).memberLastName, resultsList.get(i).memberPrimaryRole});
                    }
                    TextFirstName.setText("Enter first name...");
                    TextLastName.setText("Enter last name...");
                    ComboBoxRole.setSelectedItem("Select Role...");
                }
            } else {
                //pre exhisting - update
                String toSplit = TextMemberId.getText();
                String[] splitArray = toSplit.split(": ");      
                transitionalMember.memberId = Integer.parseInt(splitArray[1]);
                transitionalMember.projNumber = projIdGlobal;
                transitionalMember.memberFirstName= TextFirstName.getText();
                transitionalMember.memberLastName = TextLastName.getText();
                transitionalMember.memberPrimaryRole = ComboBoxRole.getSelectedItem().toString();          
                dataAccess.UpdateTeamMember(transitionalMember);  
                ArrayList<ModelTeamMember> resultsList = dataAccess.GetTeamMembers(projIdGlobal);
                    modelTeamMembersTbl.setNumRows(0);
                    for (int i = 0; i <= resultsList.size() -1; i++) {
                        modelTeamMembersTbl.addRow(new Object[]{resultsList.get(i).memberId, resultsList.get(i).memberFirstName, resultsList.get(i).memberLastName, resultsList.get(i).memberPrimaryRole});
                }
                TextFirstName.setText("Enter first name...");
                TextLastName.setText("Enter last name...");
                ComboBoxRole.setSelectedItem("Select Role...");
                String stringId = "Id: New-Member";
                TextMemberId.setText(stringId);
            }
        }
    }//GEN-LAST:event_teamMembersFuncBtnAddUpdateActionPerformed

    private void teamMembersFuncBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMembersFuncBtnResetActionPerformed
                TextFirstName.setText("Enter first name...");
                TextLastName.setText("Enter last name...");
                ComboBoxRole.setSelectedItem("Select Role...");
                String stringId = "Id: New-Member";
                TextMemberId.setText(stringId);

        
    }//GEN-LAST:event_teamMembersFuncBtnResetActionPerformed

    private void TextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFirstNameActionPerformed

    private void TextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLastNameActionPerformed

    private void teamMembersFuncBtnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMembersFuncBtnDeleteMemberActionPerformed
        JFrame frame = new JFrame("Caution");
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();
        panel.setLayout(layout);
        final JLabel label = new JLabel();
        int result = JOptionPane.showConfirmDialog(frame,"Are you sure you want to delete stakeholder?", "Caution",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION) {
            DefaultTableModel modelTeamMembersTbl = (DefaultTableModel) tableTeamMembers.getModel();
            //if single a row is selected then delete it. Multiple delete not allowed.
            if (tableTeamMembers.getSelectedRowCount() == 1) {
                int rowIndex = tableTeamMembers.getSelectedRow();
                int memberId = (int) modelTeamMembersTbl.getValueAt(rowIndex, 0);
                modelTeamMembersTbl.removeRow(rowIndex);
                dataAccess.DeleteTeamMember(memberId, projIdGlobal);
            }
        }
    }//GEN-LAST:event_teamMembersFuncBtnDeleteMemberActionPerformed
    private void teamMembersFuncBtnEditMemeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamMembersFuncBtnEditMemeberActionPerformed
        DefaultTableModel modelTeamMembersTbl = (DefaultTableModel)tableTeamMembers.getModel();
        if(tableTeamMembers.getSelectedRowCount() == 1){
            int rowIndex = tableTeamMembers.getSelectedRow();
            int memberId = (int)modelTeamMembersTbl.getValueAt(rowIndex, 0);
            String FirstName = modelTeamMembersTbl.getValueAt(rowIndex, 1).toString();
            String LastName = modelTeamMembersTbl.getValueAt(rowIndex, 2).toString();
            String Role = modelTeamMembersTbl.getValueAt(rowIndex, 3).toString();
            String stringId = "Member Id: " + memberId;
            TextMemberId.setText(stringId);
            TextFirstName.setText(FirstName);
            TextLastName.setText(LastName);
            ComboBoxRole.setSelectedItem(Role);
            
        }
    }//GEN-LAST:event_teamMembersFuncBtnEditMemeberActionPerformed

    private void TextFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFirstNameFocusGained
        String buttonInitialState = TextFirstName.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter first name...")){
            TextFirstName.setText("");
        }       
    }//GEN-LAST:event_TextFirstNameFocusGained

    private void TextFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFirstNameFocusLost
        String buttonInitialState = TextFirstName.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextFirstName.setText("Enter first name...");
        }
    }//GEN-LAST:event_TextFirstNameFocusLost

    private void TextLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextLastNameFocusGained
        String buttonInitialState = TextLastName.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter last name...")){
            TextLastName.setText("");
        } 
    }//GEN-LAST:event_TextLastNameFocusGained

    private void TextLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextLastNameFocusLost
        String buttonInitialState = TextLastName.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextLastName.setText("Enter last name...");
        }
    }//GEN-LAST:event_TextLastNameFocusLost

    private void ComboBoxRoleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRoleFocusGained

    }//GEN-LAST:event_ComboBoxRoleFocusGained

    private void ComboBoxRoleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRoleFocusLost

    }//GEN-LAST:event_ComboBoxRoleFocusLost

    private void ComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRoleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox ComboBoxRole;
    private javax.swing.JLabel LabelTotalExpended;
    private javax.swing.JLabel LabelTotalExpended1;
    private javax.swing.JLabel LabelTotalExpended2;
    private javax.swing.JLabel LabelTotalExpended3;
    private javax.swing.JLabel LabelTotalExpended4;
    private javax.swing.JLabel LabelTotalExpended6;
    private javax.swing.JLabel LabelTotalExpended7;
    private javax.swing.JLabel LabelTotalExpended8;
    private javax.swing.JTextField TextFirstName;
    private javax.swing.JTextField TextLastName;
    private javax.swing.JLabel TextMemberId;
    private javax.swing.JLabel TextProjId;
    private javax.swing.JLabel TextProjectedHrs;
    private javax.swing.JLabel TextRiskStatus;
    private javax.swing.JLabel TextStatus;
    private javax.swing.JLabel TextTotalExpended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton projectFuncBtnBack;
    private javax.swing.JButton projectFuncBtnHome;
    private TableTeamMembers tableTeamMembers;
    private javax.swing.JButton teamMembersFuncBtnAddUpdate;
    private javax.swing.JButton teamMembersFuncBtnDeleteMember;
    private javax.swing.JButton teamMembersFuncBtnEditMemeber;
    private javax.swing.JButton teamMembersFuncBtnReset;
    // End of variables declaration//GEN-END:variables
}
