import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author russe
 */
public class ViewRisks extends javax.swing.JFrame {
    DbAccess dataAccess = new DbAccess();
    int projIdGlobal = 0;
    private javax.swing.JScrollPane scroll;
    
    /**
     * Creates new form ViewTeamMembers
     * @param projIdIn
     */
    public ViewRisks(int projIdIn) {
        projIdGlobal = projIdIn;
        initComponents();
        getContentPane().setBackground(new Color(54, 69, 79));
        //begin header
        ModelProject currentProject = dataAccess.GetProject(projIdIn); 
        TextProjId.setText(Integer.toString(projIdIn)); 
        TextTotalExpended.setText(Double.toString(dataAccess.calcExpendedTotal(projIdIn)));            
        TextProjectedHrs.setText(Double.toString(dataAccess.calcProjEstimateTotal(projIdIn)));        
        int qtyRisksOutstanding = 0;        
        ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdIn);
        for(int i = 0; i <= risks.size() -1; i++){
            if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                TextRiskStatus.setText("remaining");
                qtyRisksOutstanding += 1;
            }
        }
        TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
        //End Header
        //Begin Table
        tableRisks.scrollBarUpdateTeamMembersTable(jScrollPane1);   
        DefaultTableModel modelRisksTbl = (DefaultTableModel)tableRisks.getModel();
        
        ArrayList<ModelRisk> resultsList = dataAccess.GetRisks(projIdIn);
        for (int i = 0; i <= resultsList.size() -1; i++) {
                modelRisksTbl.addRow(new Object[]{resultsList.get(i).riskId, resultsList.get(i).riskDescription, resultsList.get(i).riskStatus});
        }
        //End Table      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        projectFuncBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        projectFuncBtnHome = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        LabelTotalExpended4 = new javax.swing.JLabel();
        TextProjId = new javax.swing.JLabel();
        LabelTotalExpended3 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JLabel();
        LabelTotalExpended2 = new javax.swing.JLabel();
        TextRiskStatus = new javax.swing.JLabel();
        LabelTotalExpended1 = new javax.swing.JLabel();
        TextProjectedHrs = new javax.swing.JLabel();
        LabelTotalExpended = new javax.swing.JLabel();
        TextTotalExpended = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTotalExpended6 = new javax.swing.JLabel();
        LabelTotalExpended8 = new javax.swing.JLabel();
        TextDescription = new javax.swing.JTextField();
        riskFuncBtnReset = new javax.swing.JButton();
        riskFuncBtnAddUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxStatus = new ComboBox();
        TextRiskId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        riskFuncBtnDeleteRisk = new javax.swing.JButton();
        riskFuncBtnEditRisk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRisks = new TableTeamMembers();
        jLabel5 = new javax.swing.JLabel();

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        projectFuncBtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnBack.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnBack.setText("Back");
        projectFuncBtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmt_logo_smaill.jpg"))); // NOI18N
        jLabel1.setAlignmentY(1.0F);

        projectFuncBtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnHome.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnHome.setText("Home");
        projectFuncBtnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnHomeActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        LabelTotalExpended4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended4.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended4.setText("Proj. Id");
        LabelTotalExpended4.setToolTipText("");
        LabelTotalExpended4.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended4.setName(""); // NOI18N
        LabelTotalExpended4.setPreferredSize(new java.awt.Dimension(100, 25));

        TextProjId.setForeground(new java.awt.Color(204, 204, 204));
        TextProjId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjId.setText("0");
        TextProjId.setToolTipText("");
        TextProjId.setMinimumSize(new java.awt.Dimension(100, 25));
        TextProjId.setName(""); // NOI18N
        TextProjId.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended3.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended3.setText("Proj. Status");
        LabelTotalExpended3.setToolTipText("");
        LabelTotalExpended3.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended3.setName(""); // NOI18N
        LabelTotalExpended3.setPreferredSize(new java.awt.Dimension(100, 25));

        TextStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextStatus.setText("In-Process");
        TextStatus.setToolTipText("");
        TextStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextStatus.setName(""); // NOI18N
        TextStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended2.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended2.setText("Risks Status");
        LabelTotalExpended2.setToolTipText("");
        LabelTotalExpended2.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended2.setName(""); // NOI18N
        LabelTotalExpended2.setPreferredSize(new java.awt.Dimension(100, 25));

        TextRiskStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextRiskStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskStatus.setText("Risks Resolved");
        TextRiskStatus.setToolTipText("");
        TextRiskStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextRiskStatus.setName(""); // NOI18N
        TextRiskStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended1.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended1.setText("Projected Hours");
        LabelTotalExpended1.setToolTipText("");
        LabelTotalExpended1.setName(""); // NOI18N
        LabelTotalExpended1.setPreferredSize(new java.awt.Dimension(130, 25));

        TextProjectedHrs.setForeground(new java.awt.Color(204, 204, 204));
        TextProjectedHrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjectedHrs.setText("0");
        TextProjectedHrs.setToolTipText("");
        TextProjectedHrs.setName(""); // NOI18N
        TextProjectedHrs.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended.setText("Expended Hours");
        LabelTotalExpended.setToolTipText("");
        LabelTotalExpended.setName(""); // NOI18N
        LabelTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        TextTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        TextTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTotalExpended.setText("0");
        TextTotalExpended.setToolTipText("");
        TextTotalExpended.setName(""); // NOI18N
        TextTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Project Risks");
        jLabel3.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        LabelTotalExpended6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended6.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended6.setText("Status:");
        LabelTotalExpended6.setToolTipText("");
        LabelTotalExpended6.setName(""); // NOI18N
        LabelTotalExpended6.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended8.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended8.setText("Risk Description:");
        LabelTotalExpended8.setToolTipText("");
        LabelTotalExpended8.setName(""); // NOI18N
        LabelTotalExpended8.setPreferredSize(new java.awt.Dimension(130, 25));

        TextDescription.setForeground(new java.awt.Color(51, 51, 51));
        TextDescription.setText("Enter risk discription...");
        TextDescription.setToolTipText("");
        TextDescription.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        TextDescription.setMinimumSize(new java.awt.Dimension(64, 34));
        TextDescription.setName(""); // NOI18N
        TextDescription.setPreferredSize(new java.awt.Dimension(106, 34));
        TextDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusLost(evt);
            }
        });
        TextDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDescriptionActionPerformed(evt);
            }
        });

        riskFuncBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnReset.setForeground(new java.awt.Color(204, 0, 0));
        riskFuncBtnReset.setText("Reset");
        riskFuncBtnReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnResetActionPerformed(evt);
            }
        });

        riskFuncBtnAddUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnAddUpdate.setForeground(new java.awt.Color(0, 51, 102));
        riskFuncBtnAddUpdate.setText("Add/Update");
        riskFuncBtnAddUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnAddUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add/Edit Risk");

        ComboBoxStatus.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select status...", "Un-Resolved", "Resolved" }));
        ComboBoxStatus.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxStatus.setPreferredSize(new java.awt.Dimension(163, 33));

        TextRiskId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextRiskId.setForeground(new java.awt.Color(0, 51, 102));
        TextRiskId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskId.setText("Id: New-Risk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(riskFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(riskFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addComponent(TextRiskId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextRiskId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riskFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riskFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setToolTipText("");

        riskFuncBtnDeleteRisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnDeleteRisk.setForeground(new java.awt.Color(204, 0, 0));
        riskFuncBtnDeleteRisk.setText("Delete");
        riskFuncBtnDeleteRisk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnDeleteRisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnDeleteRiskActionPerformed(evt);
            }
        });

        riskFuncBtnEditRisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnEditRisk.setForeground(new java.awt.Color(0, 51, 102));
        riskFuncBtnEditRisk.setText("Edit");
        riskFuncBtnEditRisk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnEditRisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnEditRiskActionPerformed(evt);
            }
        });

        tableRisks.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.lightGray)));
        tableRisks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Risk Id.", "Description", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRisks);
        if (tableRisks.getColumnModel().getColumnCount() > 0) {
            tableRisks.getColumnModel().getColumn(0).setMinWidth(25);
            tableRisks.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableRisks.getColumnModel().getColumn(1).setMinWidth(25);
            tableRisks.getColumnModel().getColumn(1).setPreferredWidth(400);
            tableRisks.getColumnModel().getColumn(2).setMinWidth(25);
            tableRisks.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Risk List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(riskFuncBtnEditRisk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(riskFuncBtnDeleteRisk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riskFuncBtnEditRisk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riskFuncBtnDeleteRisk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextProjId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextRiskStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextProjectedHrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTotalExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextProjectedHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextRiskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectFuncBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnBackActionPerformed
        ViewProjectDetails vpd = new ViewProjectDetails(projIdGlobal);
        vpd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnBackActionPerformed

    private void projectFuncBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnHomeActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnHomeActionPerformed

    private void riskFuncBtnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnAddUpdateActionPerformed
        DefaultTableModel modelRisksTbl = (DefaultTableModel)tableRisks.getModel();
        ModelRisk transitionalRisk = new ModelRisk();
        String buttonInitialState = ComboBoxStatus.getSelectedItem().toString();
        if(buttonInitialState.equalsIgnoreCase("Select status...") || TextDescription.getText().equalsIgnoreCase("Enter risk discription...")){
            //do nothing except possibly notify user of condition
        }else{
            if(TextRiskId.getText().equalsIgnoreCase("Id: New-Risk")){  
               //new member - add
                transitionalRisk.riskId = 0;
                transitionalRisk.projNumber = projIdGlobal;
                transitionalRisk.riskDescription= TextDescription.getText();
                //transitionalMember.memberLastName = TextLastName.getText();
                transitionalRisk.riskStatus = ComboBoxStatus.getSelectedItem().toString();
                if(transitionalRisk.riskDescription.equalsIgnoreCase("Enter risk discription...") || transitionalRisk.riskStatus.equalsIgnoreCase("Select status...")){
                    //do nothing except send a all information required message to the user.
                } else{
                    dataAccess.InsertRisk(transitionalRisk);
                    ArrayList<ModelRisk> resultsList = dataAccess.GetRisks(projIdGlobal);
                    modelRisksTbl.setNumRows(0);
                    for (int i = 0; i <= resultsList.size() -1; i++) {
                        modelRisksTbl.addRow(new Object[]{resultsList.get(i).riskId, resultsList.get(i).riskDescription, resultsList.get(i).riskStatus});
                    }
                    TextDescription.setText("Enter risk discription...");
                    ComboBoxStatus.setSelectedItem("Select status...");
                    //update risks in the header
                    int qtyRisksOutstanding = 0;        
                    ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdGlobal);
                    for(int i = 0; i <= risks.size() -1; i++){
                        if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                            TextRiskStatus.setText("remaining");
                            qtyRisksOutstanding += 1;
                        }
                    }
                    TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
                }
            } else {
                //pre exhisting - update
                String toSplit = TextRiskId.getText();
                String[] splitArray = toSplit.split(": ");      
                transitionalRisk.riskId = Integer.parseInt(splitArray[1]);
                transitionalRisk.projNumber = projIdGlobal;
                transitionalRisk.riskDescription = TextDescription.getText();
                transitionalRisk.riskStatus = ComboBoxStatus.getSelectedItem().toString();          
                dataAccess.UpdateRisk(transitionalRisk);
                ArrayList<ModelRisk> resultsList = dataAccess.GetRisks(projIdGlobal);
                modelRisksTbl.setNumRows(0);
                for (int i = 0; i <= resultsList.size() -1; i++) {
                    modelRisksTbl.addRow(new Object[]{resultsList.get(i).riskId, resultsList.get(i).riskDescription, resultsList.get(i).riskStatus});
                }
                TextDescription.setText("Enter risk discription...");
                ComboBoxStatus.setSelectedItem("Select status...");
                String stringId = "Id: New-Risk";
                TextRiskId.setText(stringId);
                                    //update risks in the header
                    int qtyRisksOutstanding = 0;        
                    ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdGlobal);
                    for(int i = 0; i <= risks.size() -1; i++){
                        if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                            TextRiskStatus.setText("remaining");
                            qtyRisksOutstanding += 1;
                        }
                    }
                    TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
            }
        }
    }//GEN-LAST:event_riskFuncBtnAddUpdateActionPerformed

    private void riskFuncBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnResetActionPerformed
            TextDescription.setText("Enter risk discription...");
            ComboBoxStatus.setSelectedItem("Select status...");
            String stringId = "Id: New-Risk";
            TextRiskId.setText(stringId);        
    }//GEN-LAST:event_riskFuncBtnResetActionPerformed

    private void TextDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDescriptionActionPerformed

    private void riskFuncBtnDeleteRiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnDeleteRiskActionPerformed
        DefaultTableModel modelRisksTbl = (DefaultTableModel)tableRisks.getModel();
        //if single a row is selected then delete it. Multiple delete not allowed.
        if(tableRisks.getSelectedRowCount() == 1){
            int rowIndex = tableRisks.getSelectedRow();
            int riskId = (int)modelRisksTbl.getValueAt(rowIndex, 0);
            modelRisksTbl.removeRow(rowIndex);
            dataAccess.DeleteRisk(riskId, projIdGlobal);
            //update risks in the header
            int qtyRisksOutstanding = 0;        
            ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdGlobal);
                for(int i = 0; i <= risks.size() -1; i++){
                if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                TextRiskStatus.setText("remaining");
                qtyRisksOutstanding += 1;
                }
            }
            TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
        }
        
    }//GEN-LAST:event_riskFuncBtnDeleteRiskActionPerformed

    private void riskFuncBtnEditRiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnEditRiskActionPerformed
        DefaultTableModel modelRisksTbl = (DefaultTableModel)tableRisks.getModel();
        if(tableRisks.getSelectedRowCount() == 1){
            int rowIndex = tableRisks.getSelectedRow();
            int riskId = (int)modelRisksTbl.getValueAt(rowIndex, 0);
            String riskDescription = modelRisksTbl.getValueAt(rowIndex, 1).toString();
            String status = modelRisksTbl.getValueAt(rowIndex, 2).toString();
            String stringId = "Risk Id: " + riskId;
            TextRiskId.setText(stringId);
            TextDescription.setText(riskDescription);
            ComboBoxStatus.setSelectedItem(status);            
        }
        //update risks in the header
        int qtyRisksOutstanding = 0;        
        ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdGlobal);
            for(int i = 0; i <= risks.size() -1; i++){
            if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
            TextRiskStatus.setText("remaining");
            qtyRisksOutstanding += 1;
            }
        }
        TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
    }//GEN-LAST:event_riskFuncBtnEditRiskActionPerformed

    private void TextDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusGained
        String buttonInitialState = TextDescription.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter risk discription...")){
            TextDescription.setText("");
        } 
    }//GEN-LAST:event_TextDescriptionFocusGained

    private void TextDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusLost
        String buttonInitialState = TextDescription.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextDescription.setText("Enter risk discription...");
        } 

    }//GEN-LAST:event_TextDescriptionFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox ComboBoxStatus;
    private javax.swing.JLabel LabelTotalExpended;
    private javax.swing.JLabel LabelTotalExpended1;
    private javax.swing.JLabel LabelTotalExpended2;
    private javax.swing.JLabel LabelTotalExpended3;
    private javax.swing.JLabel LabelTotalExpended4;
    private javax.swing.JLabel LabelTotalExpended6;
    private javax.swing.JLabel LabelTotalExpended8;
    private javax.swing.JTextField TextDescription;
    private javax.swing.JLabel TextProjId;
    private javax.swing.JLabel TextProjectedHrs;
    private javax.swing.JLabel TextRiskId;
    private javax.swing.JLabel TextRiskStatus;
    private javax.swing.JLabel TextStatus;
    private javax.swing.JLabel TextTotalExpended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton projectFuncBtnBack;
    private javax.swing.JButton projectFuncBtnHome;
    private javax.swing.JButton riskFuncBtnAddUpdate;
    private javax.swing.JButton riskFuncBtnDeleteRisk;
    private javax.swing.JButton riskFuncBtnEditRisk;
    private javax.swing.JButton riskFuncBtnReset;
    private TableTeamMembers tableRisks;
    // End of variables declaration//GEN-END:variables
}
