import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class ViewProjectNew extends javax.swing.JFrame {
    DbAccess dataAccess = new DbAccess();    
    public ViewProjectNew() {
        initComponents();
        getContentPane().setBackground(new Color(54, 69, 79));        
        TextTotalExpended.setText("0");        
        TextProjectedHrs.setText("0");
        TextStatus.setText("In-Process");
        TextRiskStatus.setText("Resolved");
        TextProjId.setText("0");        
        TextCompanyName.setText("Enter company name...");
        TextOwner.setText("Enter owners name...");
        TextManager.setText("Enter project managers name...");
        TextDescription.setText("Enter project vision, goals, and opportunities...");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableProject1 = new TableFunctionalReqProject();
        tableProject2 = new TableFunctionalReqProject();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        projectFuncBtnBack = new javax.swing.JButton();
        projectFuncBtnHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LabelTotalExpended = new javax.swing.JLabel();
        TextTotalExpended = new javax.swing.JLabel();
        LabelTotalExpended1 = new javax.swing.JLabel();
        LabelTotalExpended2 = new javax.swing.JLabel();
        TextRiskStatus = new javax.swing.JLabel();
        LabelTotalExpended3 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JLabel();
        LabelTotalExpended4 = new javax.swing.JLabel();
        TextProjId = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescription = new javax.swing.JTextArea();
        LabelTotalExpended5 = new javax.swing.JLabel();
        TextManager = new javax.swing.JTextField();
        LabelTotalExpended6 = new javax.swing.JLabel();
        TextOwner = new javax.swing.JTextField();
        LabelTotalExpended7 = new javax.swing.JLabel();
        LabelTotalExpended8 = new javax.swing.JLabel();
        TextCompanyName = new javax.swing.JTextField();
        projectFuncBtnReset = new javax.swing.JButton();
        projectFuncBtnUpdate = new javax.swing.JButton();
        TextProjectedHrs = new javax.swing.JTextField();
        LabelTotalExpended10 = new javax.swing.JLabel();
        TextPlaceHolder = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Functional Requirements");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmt_logo_smaill.jpg"))); // NOI18N
        jLabel1.setAlignmentY(1.0F);

        projectFuncBtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnBack.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnBack.setText("Back");
        projectFuncBtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnBackActionPerformed(evt);
            }
        });

        projectFuncBtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnHome.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnHome.setText("Home");
        projectFuncBtnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnHomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Project Details");
        jLabel3.setToolTipText("");

        LabelTotalExpended.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended.setText("Expended Hours");
        LabelTotalExpended.setToolTipText("");
        LabelTotalExpended.setName(""); // NOI18N
        LabelTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        TextTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        TextTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTotalExpended.setText("0");
        TextTotalExpended.setToolTipText("");
        TextTotalExpended.setName(""); // NOI18N
        TextTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended1.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended1.setText("Projected Hours");
        LabelTotalExpended1.setToolTipText("");
        LabelTotalExpended1.setName(""); // NOI18N
        LabelTotalExpended1.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended2.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended2.setText("Risks Status");
        LabelTotalExpended2.setToolTipText("");
        LabelTotalExpended2.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended2.setName(""); // NOI18N
        LabelTotalExpended2.setPreferredSize(new java.awt.Dimension(100, 25));

        TextRiskStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextRiskStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskStatus.setText("Risks Resolved");
        TextRiskStatus.setToolTipText("");
        TextRiskStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextRiskStatus.setName(""); // NOI18N
        TextRiskStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended3.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended3.setText("Proj. Status");
        LabelTotalExpended3.setToolTipText("");
        LabelTotalExpended3.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended3.setName(""); // NOI18N
        LabelTotalExpended3.setPreferredSize(new java.awt.Dimension(100, 25));

        TextStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextStatus.setText("In-Process");
        TextStatus.setToolTipText("");
        TextStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextStatus.setName(""); // NOI18N
        TextStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended4.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended4.setText("Proj. Id");
        LabelTotalExpended4.setToolTipText("");
        LabelTotalExpended4.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended4.setName(""); // NOI18N
        LabelTotalExpended4.setPreferredSize(new java.awt.Dimension(100, 25));

        TextProjId.setForeground(new java.awt.Color(204, 204, 204));
        TextProjId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjId.setText("0");
        TextProjId.setToolTipText("");
        TextProjId.setMinimumSize(new java.awt.Dimension(100, 25));
        TextProjId.setName(""); // NOI18N
        TextProjId.setPreferredSize(new java.awt.Dimension(100, 25));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        TextDescription.setColumns(20);
        TextDescription.setForeground(new java.awt.Color(51, 51, 51));
        TextDescription.setLineWrap(true);
        TextDescription.setRows(5);
        TextDescription.setText("Enter project vision, goals, and opportunities...");
        TextDescription.setWrapStyleWord(true);
        TextDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(TextDescription);

        LabelTotalExpended5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended5.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended5.setText("Project Description:");
        LabelTotalExpended5.setToolTipText("");
        LabelTotalExpended5.setName(""); // NOI18N
        LabelTotalExpended5.setPreferredSize(new java.awt.Dimension(130, 25));

        TextManager.setForeground(new java.awt.Color(51, 51, 51));
        TextManager.setText("Enter managers name...");
        TextManager.setToolTipText("");
        TextManager.setMinimumSize(new java.awt.Dimension(64, 25));
        TextManager.setName(""); // NOI18N
        TextManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextManagerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextManagerFocusLost(evt);
            }
        });
        TextManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextManagerActionPerformed(evt);
            }
        });

        LabelTotalExpended6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended6.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended6.setText("Project Manager:");
        LabelTotalExpended6.setToolTipText("");
        LabelTotalExpended6.setName(""); // NOI18N
        LabelTotalExpended6.setPreferredSize(new java.awt.Dimension(130, 25));

        TextOwner.setForeground(new java.awt.Color(51, 51, 51));
        TextOwner.setText("Enter owners name...");
        TextOwner.setToolTipText("");
        TextOwner.setMinimumSize(new java.awt.Dimension(64, 25));
        TextOwner.setName(""); // NOI18N
        TextOwner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextOwnerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextOwnerFocusLost(evt);
            }
        });
        TextOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOwnerActionPerformed(evt);
            }
        });

        LabelTotalExpended7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended7.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended7.setText("Project Owner:");
        LabelTotalExpended7.setToolTipText("");
        LabelTotalExpended7.setName(""); // NOI18N
        LabelTotalExpended7.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended8.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended8.setText("Client/Company Name:");
        LabelTotalExpended8.setToolTipText("");
        LabelTotalExpended8.setName(""); // NOI18N
        LabelTotalExpended8.setPreferredSize(new java.awt.Dimension(130, 25));

        TextCompanyName.setForeground(new java.awt.Color(51, 51, 51));
        TextCompanyName.setText("Enter company name...");
        TextCompanyName.setToolTipText("");
        TextCompanyName.setMinimumSize(new java.awt.Dimension(64, 25));
        TextCompanyName.setName(""); // NOI18N
        TextCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextCompanyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextCompanyNameFocusLost(evt);
            }
        });
        TextCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompanyNameActionPerformed(evt);
            }
        });

        projectFuncBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectFuncBtnReset.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnReset.setText("Reset");
        projectFuncBtnReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnResetActionPerformed(evt);
            }
        });

        projectFuncBtnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectFuncBtnUpdate.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnUpdate.setText("Save");
        projectFuncBtnUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnUpdateActionPerformed(evt);
            }
        });

        TextProjectedHrs.setForeground(new java.awt.Color(51, 51, 51));
        TextProjectedHrs.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextProjectedHrs.setText("0");
        TextProjectedHrs.setMinimumSize(new java.awt.Dimension(64, 25));
        TextProjectedHrs.setPreferredSize(new java.awt.Dimension(64, 25));
        TextProjectedHrs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextProjectedHrsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextProjectedHrsFocusLost(evt);
            }
        });

        LabelTotalExpended10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended10.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalExpended10.setText("Projected Hours");
        LabelTotalExpended10.setToolTipText("");
        LabelTotalExpended10.setName(""); // NOI18N
        LabelTotalExpended10.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTotalExpended10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextProjectedHrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelTotalExpended5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(projectFuncBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(projectFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextManager, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProjectedHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotalExpended10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTotalExpended5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectFuncBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        TextPlaceHolder.setForeground(new java.awt.Color(204, 204, 204));
        TextPlaceHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPlaceHolder.setText("0");
        TextPlaceHolder.setToolTipText("");
        TextPlaceHolder.setName(""); // NOI18N
        TextPlaceHolder.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(139, 139, 139)
                                .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextProjId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextRiskStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextPlaceHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTotalExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextRiskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectFuncBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnResetActionPerformed
        TextTotalExpended.setText("0");        
        TextProjectedHrs.setText("0");
        TextRiskStatus.setText("Resolved");
        TextStatus.setText("In-Process");
        TextProjId.setText("0");        
        TextCompanyName.setText("Enter company name...");
        TextOwner.setText("Enter owners name...");
        TextManager.setText("Enter project managers name...");
        TextDescription.setText("Enter project vision, goals, and opportunities...");
     
    }//GEN-LAST:event_projectFuncBtnResetActionPerformed

    private void projectFuncBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnUpdateActionPerformed
        ModelProject currentProj = new ModelProject();
        currentProj.companyName = TextCompanyName.getText();
        currentProj.projOwner = TextOwner.getText();
        currentProj.projManager = TextManager.getText();
        currentProj.projDescription = TextDescription.getText();
        currentProj.projEstimatedHours = TextProjectedHrs.getText();
        currentProj.projStatus = TextStatus.getText();
        if(currentProj.companyName.equalsIgnoreCase("Enter company name...") || 
           currentProj.projDescription.equalsIgnoreCase("Enter project vision, goals, and opportunities...") ||
           currentProj.projManager.equalsIgnoreCase("Enter project managers name...") ||
           currentProj.projOwner.equalsIgnoreCase("Enter owners name..."))
        {             
            //do nothing
            //possibly return error to user
        } else {
            ModelProject returnedProject = dataAccess.InsertProject(currentProj);            
            ViewProjectDetails vpd = new ViewProjectDetails(returnedProject.projId);
            vpd.setVisible(true);
            this.dispose();
        }        
    }//GEN-LAST:event_projectFuncBtnUpdateActionPerformed

    private void projectFuncBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnBackActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnBackActionPerformed

    private void projectFuncBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnHomeActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_projectFuncBtnHomeActionPerformed

    private void TextManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextManagerActionPerformed

    private void TextOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextOwnerActionPerformed

    private void TextCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompanyNameActionPerformed

    private void TextCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCompanyNameFocusGained
        String buttonInitialState = TextCompanyName.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter company name...")){
            TextCompanyName.setText("");
        } 
    }//GEN-LAST:event_TextCompanyNameFocusGained

    private void TextCompanyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCompanyNameFocusLost
        String buttonInitialState = TextCompanyName.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextCompanyName.setText("Enter company name...");
        } 
    }//GEN-LAST:event_TextCompanyNameFocusLost

    private void TextOwnerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextOwnerFocusGained
        String buttonInitialState = TextOwner.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter owners name...")){
            TextOwner.setText("");
        }
    }//GEN-LAST:event_TextOwnerFocusGained

    private void TextOwnerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextOwnerFocusLost
        String buttonInitialState = TextOwner.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextOwner.setText("Enter owners name...");
        }    
    }//GEN-LAST:event_TextOwnerFocusLost

    private void TextManagerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextManagerFocusGained
        String buttonInitialState = TextManager.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter project managers name...")){
            TextManager.setText("");
        } 
    }//GEN-LAST:event_TextManagerFocusGained

    private void TextManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextManagerFocusLost
        String buttonInitialState = TextManager.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextManager.setText("Enter project managers name...");
        } 
    }//GEN-LAST:event_TextManagerFocusLost

    private void TextProjectedHrsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProjectedHrsFocusGained
        String buttonInitialState = TextProjectedHrs.getText();
        if(buttonInitialState.equalsIgnoreCase("0")){
            TextProjectedHrs.setText("");
        } 

    }//GEN-LAST:event_TextProjectedHrsFocusGained

    private void TextProjectedHrsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProjectedHrsFocusLost
        String buttonInitialState = TextProjectedHrs.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextProjectedHrs.setText("0");
        }   
    }//GEN-LAST:event_TextProjectedHrsFocusLost

    private void TextDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusGained
        String buttonInitialState = TextDescription.getText();
        if(buttonInitialState.equalsIgnoreCase("Enter project vision, goals, and opportunities...")){
            TextDescription.setText("");
        } 
    }//GEN-LAST:event_TextDescriptionFocusGained

    private void TextDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusLost
        String buttonInitialState = TextDescription.getText();
        if(buttonInitialState.equalsIgnoreCase("")){
            TextDescription.setText("Enter project vision, goals, and opportunities...");
        } 
    }//GEN-LAST:event_TextDescriptionFocusLost
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTotalExpended;
    private javax.swing.JLabel LabelTotalExpended1;
    private javax.swing.JLabel LabelTotalExpended10;
    private javax.swing.JLabel LabelTotalExpended2;
    private javax.swing.JLabel LabelTotalExpended3;
    private javax.swing.JLabel LabelTotalExpended4;
    private javax.swing.JLabel LabelTotalExpended5;
    private javax.swing.JLabel LabelTotalExpended6;
    private javax.swing.JLabel LabelTotalExpended7;
    private javax.swing.JLabel LabelTotalExpended8;
    private javax.swing.JTextField TextCompanyName;
    private javax.swing.JTextArea TextDescription;
    private javax.swing.JTextField TextManager;
    private javax.swing.JTextField TextOwner;
    private javax.swing.JLabel TextPlaceHolder;
    private javax.swing.JLabel TextProjId;
    private javax.swing.JTextField TextProjectedHrs;
    private javax.swing.JLabel TextRiskStatus;
    private javax.swing.JLabel TextStatus;
    private javax.swing.JLabel TextTotalExpended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton projectFuncBtnBack;
    private javax.swing.JButton projectFuncBtnHome;
    private javax.swing.JButton projectFuncBtnReset;
    private javax.swing.JButton projectFuncBtnUpdate;
    private TableFunctionalReqProject tableProject1;
    private TableFunctionalReqProject tableProject2;
    // End of variables declaration//GEN-END:variables
}
