import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author russe
 */
public class ViewUpdateHoursExpended extends javax.swing.JFrame {
    DbAccess dataAccess = new DbAccess();
    int projIdGlobal = 0;
    int reqIdGlobal = 0;
    private javax.swing.JScrollPane scroll;
    
    /**
     * Creates new form ViewTeamMembers
     * @param projIdIn
     * @param reqIdIn
     */
    public ViewUpdateHoursExpended(int projIdIn, int reqIdIn) {
        projIdGlobal = projIdIn;
        reqIdGlobal = reqIdIn;
        initComponents();
        getContentPane().setBackground(new Color(54, 69, 79));
        //begin header
        TextProjId.setText(Integer.toString(projIdIn)); 
        TextTotalExpended.setText(Double.toString(dataAccess.calcExpendedTotal(projIdIn)));            
        TextProjectedHrs.setText(Double.toString(dataAccess.calcProjEstimateTotal(projIdIn)));        
        int qtyRisksOutstanding = 0;        
        ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdIn);
        for(int i = 0; i <= risks.size() -1; i++){
            if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                TextRiskStatus.setText("remaining");
                qtyRisksOutstanding += 1;
            }
        }
        TextRiskStatus.setText(qtyRisksOutstanding + " Outstanding");
        //End Header
        ArrayList<ModelTeamMember> resultantMemberList = dataAccess.GetTeamMembers(projIdIn);
        for (int i = 0; i <= resultantMemberList.size() -1; i++) {
            String fName = resultantMemberList.get(i).memberFirstName;
            String lName = resultantMemberList.get(i).memberLastName;
            String fullName = fName + " " + lName;
            ComboBoxMember.addItem(fullName);
        }
        //Begin Table
        tableHoursExpended.scrollBarUpdateTeamMembersTable(jScrollPane3);   
        DefaultTableModel modelExpHoursTbl = (DefaultTableModel)tableHoursExpended.getModel();        
        ArrayList<ModelExpendedHours> resultsList = dataAccess.GetExpendedHours(reqIdGlobal);
        for (int i = 0; i <= resultsList.size() -1; i++) {
                String enteredBy = resultsList.get(i).memberFirstName + " " + resultsList.get(i).memberLastName;
                modelExpHoursTbl.addRow(new Object[]{resultsList.get(i).expId, resultsList.get(i).projNumber, resultsList.get(i).reqNumber,
                enteredBy,resultsList.get(i).expDescription,  resultsList.get(i).expHoursType, resultsList.get(i).expNumHours});
        }
        //End Table      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        projectFuncBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        projectFuncBtnHome = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        LabelTotalExpended4 = new javax.swing.JLabel();
        TextProjId = new javax.swing.JLabel();
        LabelTotalExpended3 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JLabel();
        LabelTotalExpended2 = new javax.swing.JLabel();
        TextRiskStatus = new javax.swing.JLabel();
        LabelTotalExpended1 = new javax.swing.JLabel();
        TextProjectedHrs = new javax.swing.JLabel();
        LabelTotalExpended = new javax.swing.JLabel();
        TextTotalExpended = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTotalExpended6 = new javax.swing.JLabel();
        LabelTotalExpended8 = new javax.swing.JLabel();
        riskFuncBtnReset = new javax.swing.JButton();
        riskFuncBtnAddUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxWorkType = new ComboBox();
        TextExpId = new javax.swing.JLabel();
        LabelTotalExpended9 = new javax.swing.JLabel();
        TextHoursExpended = new javax.swing.JTextField();
        LabelTotalExpended7 = new javax.swing.JLabel();
        ComboBoxMember = new ComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextDescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        riskFuncBtnDeleteEntry = new javax.swing.JButton();
        riskFuncBtnEditEntry = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHoursExpended = new TableHoursExpended();

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        projectFuncBtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnBack.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnBack.setText("Back");
        projectFuncBtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmt_logo_smaill.jpg"))); // NOI18N
        jLabel1.setAlignmentY(1.0F);

        projectFuncBtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnHome.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnHome.setText("Home");
        projectFuncBtnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnHomeActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        LabelTotalExpended4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended4.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended4.setText("Proj. Id");
        LabelTotalExpended4.setToolTipText("");
        LabelTotalExpended4.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended4.setName(""); // NOI18N
        LabelTotalExpended4.setPreferredSize(new java.awt.Dimension(100, 25));

        TextProjId.setForeground(new java.awt.Color(204, 204, 204));
        TextProjId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjId.setText("0");
        TextProjId.setToolTipText("");
        TextProjId.setMinimumSize(new java.awt.Dimension(100, 25));
        TextProjId.setName(""); // NOI18N
        TextProjId.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended3.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended3.setText("Proj. Status");
        LabelTotalExpended3.setToolTipText("");
        LabelTotalExpended3.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended3.setName(""); // NOI18N
        LabelTotalExpended3.setPreferredSize(new java.awt.Dimension(100, 25));

        TextStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextStatus.setText("In-Process");
        TextStatus.setToolTipText("");
        TextStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextStatus.setName(""); // NOI18N
        TextStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended2.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended2.setText("Risks Status");
        LabelTotalExpended2.setToolTipText("");
        LabelTotalExpended2.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended2.setName(""); // NOI18N
        LabelTotalExpended2.setPreferredSize(new java.awt.Dimension(100, 25));

        TextRiskStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextRiskStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskStatus.setText("Risks Resolved");
        TextRiskStatus.setToolTipText("");
        TextRiskStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextRiskStatus.setName(""); // NOI18N
        TextRiskStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended1.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended1.setText("Projected Hours");
        LabelTotalExpended1.setToolTipText("");
        LabelTotalExpended1.setName(""); // NOI18N
        LabelTotalExpended1.setPreferredSize(new java.awt.Dimension(130, 25));

        TextProjectedHrs.setForeground(new java.awt.Color(204, 204, 204));
        TextProjectedHrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjectedHrs.setText("0");
        TextProjectedHrs.setToolTipText("");
        TextProjectedHrs.setName(""); // NOI18N
        TextProjectedHrs.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended.setText("Expended Hours");
        LabelTotalExpended.setToolTipText("");
        LabelTotalExpended.setName(""); // NOI18N
        LabelTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        TextTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        TextTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTotalExpended.setText("0");
        TextTotalExpended.setToolTipText("");
        TextTotalExpended.setName(""); // NOI18N
        TextTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Project Hours Expended");
        jLabel3.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        LabelTotalExpended6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended6.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended6.setText("Work Type:");
        LabelTotalExpended6.setToolTipText("");
        LabelTotalExpended6.setName(""); // NOI18N
        LabelTotalExpended6.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended8.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended8.setText("Work Description:");
        LabelTotalExpended8.setToolTipText("");
        LabelTotalExpended8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelTotalExpended8.setName(""); // NOI18N
        LabelTotalExpended8.setPreferredSize(new java.awt.Dimension(130, 25));

        riskFuncBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnReset.setForeground(new java.awt.Color(204, 0, 0));
        riskFuncBtnReset.setText("Reset");
        riskFuncBtnReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnResetActionPerformed(evt);
            }
        });

        riskFuncBtnAddUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnAddUpdate.setForeground(new java.awt.Color(0, 51, 102));
        riskFuncBtnAddUpdate.setText("Add/Update");
        riskFuncBtnAddUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnAddUpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add/Edit New");

        ComboBoxWorkType.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxWorkType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type...", "Project Management", "Business Analysis", "Requirements Gathering", "Requirements Documentation", "System Design", "UI Design", "UX Design", "Prototyping", "UML Diagraming", "Database Design", "Consultation", "Client Presentation", "Testing", "Quality Assurance", "Technical Support" }));
        ComboBoxWorkType.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxWorkType.setPreferredSize(new java.awt.Dimension(163, 33));
        ComboBoxWorkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxWorkTypeActionPerformed(evt);
            }
        });

        TextExpId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextExpId.setForeground(new java.awt.Color(0, 51, 102));
        TextExpId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextExpId.setText("Expended Id: New-Entry");

        LabelTotalExpended9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended9.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended9.setText("Hours Expended:");
        LabelTotalExpended9.setToolTipText("");
        LabelTotalExpended9.setName(""); // NOI18N
        LabelTotalExpended9.setPreferredSize(new java.awt.Dimension(130, 25));

        TextHoursExpended.setForeground(new java.awt.Color(51, 51, 51));
        TextHoursExpended.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextHoursExpended.setText("0");
        TextHoursExpended.setToolTipText("");
        TextHoursExpended.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        TextHoursExpended.setMinimumSize(new java.awt.Dimension(64, 34));
        TextHoursExpended.setName(""); // NOI18N
        TextHoursExpended.setPreferredSize(new java.awt.Dimension(106, 34));
        TextHoursExpended.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextHoursExpendedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextHoursExpendedFocusLost(evt);
            }
        });
        TextHoursExpended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHoursExpendedActionPerformed(evt);
            }
        });

        LabelTotalExpended7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended7.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended7.setText("Team Member Name:");
        LabelTotalExpended7.setToolTipText("");
        LabelTotalExpended7.setName(""); // NOI18N
        LabelTotalExpended7.setPreferredSize(new java.awt.Dimension(130, 25));

        ComboBoxMember.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxMember.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select member..." }));
        ComboBoxMember.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxMember.setPreferredSize(new java.awt.Dimension(163, 33));

        TextDescription.setColumns(20);
        TextDescription.setLineWrap(true);
        TextDescription.setRows(3);
        TextDescription.setTabSize(50);
        TextDescription.setText("Enter work description...");
        TextDescription.setToolTipText("");
        TextDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextDescriptionFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(TextDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TextExpId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTotalExpended9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextHoursExpended, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxMember, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxWorkType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(riskFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(riskFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextExpId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelTotalExpended8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTotalExpended9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(TextHoursExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxWorkType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxMember, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riskFuncBtnAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riskFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setToolTipText("");

        riskFuncBtnDeleteEntry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnDeleteEntry.setForeground(new java.awt.Color(204, 0, 0));
        riskFuncBtnDeleteEntry.setText("Delete");
        riskFuncBtnDeleteEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnDeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnDeleteEntryActionPerformed(evt);
            }
        });

        riskFuncBtnEditEntry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        riskFuncBtnEditEntry.setForeground(new java.awt.Color(0, 51, 102));
        riskFuncBtnEditEntry.setText("Edit");
        riskFuncBtnEditEntry.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        riskFuncBtnEditEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskFuncBtnEditEntryActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hours Expended Log");

        tableHoursExpended.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exp. Id", "Proj. Id", "Req. Id", "Entered by", "Work Description", "Work Type", "Hrs."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableHoursExpended);
        if (tableHoursExpended.getColumnModel().getColumnCount() > 0) {
            tableHoursExpended.getColumnModel().getColumn(0).setMinWidth(5);
            tableHoursExpended.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableHoursExpended.getColumnModel().getColumn(1).setMinWidth(5);
            tableHoursExpended.getColumnModel().getColumn(1).setPreferredWidth(20);
            tableHoursExpended.getColumnModel().getColumn(2).setMinWidth(5);
            tableHoursExpended.getColumnModel().getColumn(2).setPreferredWidth(20);
            tableHoursExpended.getColumnModel().getColumn(3).setMinWidth(25);
            tableHoursExpended.getColumnModel().getColumn(3).setPreferredWidth(100);
            tableHoursExpended.getColumnModel().getColumn(4).setMinWidth(25);
            tableHoursExpended.getColumnModel().getColumn(4).setPreferredWidth(400);
            tableHoursExpended.getColumnModel().getColumn(5).setMinWidth(25);
            tableHoursExpended.getColumnModel().getColumn(5).setPreferredWidth(75);
            tableHoursExpended.getColumnModel().getColumn(6).setMinWidth(10);
            tableHoursExpended.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(riskFuncBtnEditEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(riskFuncBtnDeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riskFuncBtnEditEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riskFuncBtnDeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextProjId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextRiskStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TextProjectedHrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTotalExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1)
                                .addGap(140, 140, 140)
                                .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextProjectedHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextRiskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectFuncBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnBackActionPerformed
        ViewEditRequirementDetails vrd = new ViewEditRequirementDetails(projIdGlobal,reqIdGlobal);
        vrd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnBackActionPerformed

    private void projectFuncBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnHomeActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnHomeActionPerformed

    private void riskFuncBtnAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnAddUpdateActionPerformed
        DefaultTableModel modelExpHoursTbl = (DefaultTableModel)tableHoursExpended.getModel();        
        ModelExpendedHours transitionalExpHoursRecord = new ModelExpendedHours();
        String ComboBoxWorkInitState = ComboBoxWorkType.getSelectedItem().toString();
        String ComboBoxMemberInitState = ComboBoxMember.getSelectedItem().toString();
        if(ComboBoxWorkInitState.equalsIgnoreCase("Select type...") ||ComboBoxMemberInitState.equalsIgnoreCase("Select member...") || TextDescription.getText().equalsIgnoreCase("Enter work description...")){
            //do nothing except possibly notify user of condition
        }else{
            if(TextExpId.getText().equalsIgnoreCase("Expended Id: New-Entry")){  
               //new member - add
                String[] teamMemberName = ComboBoxMember.getSelectedItem().toString().split(" ",2);
                String firstName = teamMemberName[0];
                String lastName = teamMemberName[1];
                transitionalExpHoursRecord.expId = 0;
                transitionalExpHoursRecord.projNumber = projIdGlobal;
                transitionalExpHoursRecord.reqNumber = reqIdGlobal;
                transitionalExpHoursRecord.expDescription= TextDescription.getText();
                transitionalExpHoursRecord.memberFirstName = firstName;
                transitionalExpHoursRecord.memberLastName = lastName;
                transitionalExpHoursRecord.expHoursType = ComboBoxWorkType.getSelectedItem().toString();
                transitionalExpHoursRecord.expNumHours = Double.parseDouble(TextHoursExpended.getText());
                if(transitionalExpHoursRecord.expDescription.equalsIgnoreCase("Enter work description...") ||
                        transitionalExpHoursRecord.memberFirstName.equalsIgnoreCase("Select") ||
                        transitionalExpHoursRecord.expHoursType.equalsIgnoreCase("Select type...")){
                    //do nothing except send a all information required message to the user.
                } else{
                    dataAccess.InsertExpendedHours(transitionalExpHoursRecord);
                    ArrayList<ModelExpendedHours> resultsList = dataAccess.GetExpendedHours(reqIdGlobal);
                    modelExpHoursTbl.setNumRows(0);
                    for (int i = 0; i <= resultsList.size() -1; i++) {
                            String enteredBy = resultsList.get(i).memberFirstName + " " + resultsList.get(i).memberLastName;
                            modelExpHoursTbl.addRow(new Object[]{resultsList.get(i).expId, resultsList.get(i).projNumber, resultsList.get(i).reqNumber,
                            enteredBy,resultsList.get(i).expDescription,  resultsList.get(i).expHoursType, resultsList.get(i).expNumHours});
                    }
                    TextDescription.setText("Enter work description...");
                    ComboBoxWorkType.setSelectedItem("Select type...");
                    ComboBoxMember.setSelectedItem("Select member...");
                    TextHoursExpended.setText("0");
                    String stringId = "Expended Id: New-Entry";
                    TextExpId.setText(stringId);
                }
            } else {
                //pre exhisting - update
                String[] teamMemberName = ComboBoxMember.getSelectedItem().toString().split(" ",2);
                String firstName = teamMemberName[0];
                String lastName = teamMemberName[1];
                String toSplit = TextExpId.getText();
                String[] splitArray = toSplit.split(": "); 
                transitionalExpHoursRecord.expId = Integer.parseInt(splitArray[1]);
                transitionalExpHoursRecord.projNumber = projIdGlobal;
                transitionalExpHoursRecord.reqNumber = reqIdGlobal;
                transitionalExpHoursRecord.expDescription= TextDescription.getText();
                transitionalExpHoursRecord.memberFirstName = firstName;
                transitionalExpHoursRecord.memberLastName = lastName;
                transitionalExpHoursRecord.expHoursType = ComboBoxWorkType.getSelectedItem().toString();

                transitionalExpHoursRecord.expNumHours = Double.parseDouble(TextHoursExpended.getText());
                ArrayList<ModelExpendedHours> resultsList = dataAccess.UpdateExpendedHoursRecord(transitionalExpHoursRecord);
                modelExpHoursTbl.setNumRows(0);
                for (int i = 0; i <= resultsList.size() -1; i++) {
                        String enteredBy = resultsList.get(i).memberFirstName + " " + resultsList.get(i).memberLastName;
                        modelExpHoursTbl.addRow(new Object[]{resultsList.get(i).expId, resultsList.get(i).projNumber, resultsList.get(i).reqNumber,
                        enteredBy,resultsList.get(i).expDescription,  resultsList.get(i).expHoursType, resultsList.get(i).expNumHours});
                }
                
                
                TextDescription.setText("Enter work description...");
                ComboBoxWorkType.setSelectedItem("Select type...");
                ComboBoxMember.setSelectedItem("Select member...");
                TextHoursExpended.setText("0");
                String stringId = "Expended Id: New-Entry";
                TextExpId.setText(stringId);
            }
        }
    }//GEN-LAST:event_riskFuncBtnAddUpdateActionPerformed

    private void riskFuncBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnResetActionPerformed
            TextDescription.setText("Enter work description...");
            ComboBoxWorkType.setSelectedItem("Select type...");
            ComboBoxMember.setSelectedItem("Select member...");
            TextHoursExpended.setText("0");
            String stringId = "Expended Id: New-Entry";
            TextExpId.setText(stringId);        
    }//GEN-LAST:event_riskFuncBtnResetActionPerformed

    private void riskFuncBtnDeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnDeleteEntryActionPerformed
        DefaultTableModel modelExpHoursTbl = (DefaultTableModel)tableHoursExpended.getModel();
        //if single a row is selected then delete it. Multiple delete not allowed.
        if(tableHoursExpended.getSelectedRowCount() == 1){
            int rowIndex = tableHoursExpended.getSelectedRow();
            int riskId = (int)modelExpHoursTbl.getValueAt(rowIndex, 0);
            modelExpHoursTbl.removeRow(rowIndex);
            dataAccess.DeleteRisk(riskId, projIdGlobal);
        }
    }//GEN-LAST:event_riskFuncBtnDeleteEntryActionPerformed

    private void riskFuncBtnEditEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskFuncBtnEditEntryActionPerformed
        DefaultTableModel modelExpHoursTbl = (DefaultTableModel)tableHoursExpended.getModel();
        if(tableHoursExpended.getSelectedRowCount() == 1){
            int rowIndex = tableHoursExpended.getSelectedRow();
            int riskId = (int)modelExpHoursTbl.getValueAt(rowIndex, 0);
            String expDescription = modelExpHoursTbl.getValueAt(rowIndex, 4).toString();
            String workType = modelExpHoursTbl.getValueAt(rowIndex, 5).toString();
            String memberName = modelExpHoursTbl.getValueAt(rowIndex, 3).toString();
            String hoursExpended = modelExpHoursTbl.getValueAt(rowIndex, 6).toString();
            String stringId = "Expended Id: " + riskId;
            TextExpId.setText(stringId);
            TextDescription.setText(expDescription);
            TextHoursExpended.setText(hoursExpended);
            ComboBoxWorkType.setSelectedItem(workType); 
            ComboBoxMember.setSelectedItem(memberName);
        }
    }//GEN-LAST:event_riskFuncBtnEditEntryActionPerformed

    private void TextHoursExpendedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextHoursExpendedFocusGained
        String InitialState = TextHoursExpended.getText();
        if(InitialState.equalsIgnoreCase("0")){
            TextHoursExpended.setText("");
        }
    }//GEN-LAST:event_TextHoursExpendedFocusGained

    private void TextHoursExpendedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextHoursExpendedFocusLost
        String InitialState = TextHoursExpended.getText();
        if(InitialState.equalsIgnoreCase("")){
            TextHoursExpended.setText("0");
        }
    }//GEN-LAST:event_TextHoursExpendedFocusLost

    private void TextHoursExpendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHoursExpendedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHoursExpendedActionPerformed

    private void ComboBoxWorkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxWorkTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxWorkTypeActionPerformed

    private void TextDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusGained
        String InitialState = TextDescription.getText();
        if(InitialState.equalsIgnoreCase("Enter work description...")){
            TextDescription.setText("");
        }
    }//GEN-LAST:event_TextDescriptionFocusGained

    private void TextDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescriptionFocusLost
        String InitialState = TextDescription.getText();
        if(InitialState.equalsIgnoreCase("")){
            TextDescription.setText("Enter work description...");
        }

    }//GEN-LAST:event_TextDescriptionFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox ComboBoxMember;
    private ComboBox ComboBoxWorkType;
    private javax.swing.JLabel LabelTotalExpended;
    private javax.swing.JLabel LabelTotalExpended1;
    private javax.swing.JLabel LabelTotalExpended2;
    private javax.swing.JLabel LabelTotalExpended3;
    private javax.swing.JLabel LabelTotalExpended4;
    private javax.swing.JLabel LabelTotalExpended6;
    private javax.swing.JLabel LabelTotalExpended7;
    private javax.swing.JLabel LabelTotalExpended8;
    private javax.swing.JLabel LabelTotalExpended9;
    private javax.swing.JTextArea TextDescription;
    private javax.swing.JLabel TextExpId;
    private javax.swing.JTextField TextHoursExpended;
    private javax.swing.JLabel TextProjId;
    private javax.swing.JLabel TextProjectedHrs;
    private javax.swing.JLabel TextRiskStatus;
    private javax.swing.JLabel TextStatus;
    private javax.swing.JLabel TextTotalExpended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton projectFuncBtnBack;
    private javax.swing.JButton projectFuncBtnHome;
    private javax.swing.JButton riskFuncBtnAddUpdate;
    private javax.swing.JButton riskFuncBtnDeleteEntry;
    private javax.swing.JButton riskFuncBtnEditEntry;
    private javax.swing.JButton riskFuncBtnReset;
    private TableHoursExpended tableHoursExpended;
    // End of variables declaration//GEN-END:variables
}
