          import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author russe
 */
public class ViewEditRequirementDetails extends javax.swing.JFrame {
    DbAccess dataAccess = new DbAccess();
    int projIdGlobal = 0;
    int reqIdGlobal = 0;
    private javax.swing.JScrollPane scroll;
    
    /**
     * Creates new form ViewTeamMembers
     * @param projIdIn
     */
    public ViewEditRequirementDetails(int projIdIn, int reqIdIn) {
        projIdGlobal = projIdIn;
        reqIdGlobal = reqIdIn;
        initComponents();
        getContentPane().setBackground(new Color(54, 69, 79));
        //Begin Header
        TextTotalExpended.setText(Integer.toString(dataAccess.calcExpendedTotal(projIdIn)));
        ModelProject currentProject = dataAccess.GetProject(projIdIn);        
        TextProjectedHrs.setText(currentProject.projEstimatedHours);
        TextRiskStatus.setText(currentProject.projStatus);
        TextProjId.setText(Integer.toString(projIdIn));        
        ArrayList<ModelRisk> risks = dataAccess.GetRisks(projIdIn);
        for(int i = 0; i <= risks.size() -1; i++){
            if(risks.get(i).riskStatus.equalsIgnoreCase("Un-Resolved")){
                TextRiskStatus.setText("Risks Oustanding");
            }
        }
        //End Header
        //Begin details
        ModelRequirement reqModel = dataAccess.GetRequirement(reqIdIn);
        TextRequirementId.setText(String.valueOf(reqIdIn));
        TextRequirementExpenedHours.setText(String.valueOf(dataAccess.GetRequirementExpendedHours(reqIdIn)));
        TextRequirementEstimatedHours.setText(String.valueOf(dataAccess.GetRequirementEstimatedHours(reqIdIn)));
        ComboBoxRequirementType.setSelectedItem(reqModel.reqType);
        ComboBoxRequirementStatus.setSelectedItem(reqModel.reqStatus);
        TextRequirementDescription.setText(reqModel.reqDescription);
        //End details
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        projectFuncBtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        projectFuncBtnHome = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        LabelTotalExpended4 = new javax.swing.JLabel();
        TextProjId = new javax.swing.JLabel();
        LabelTotalExpended3 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JLabel();
        LabelTotalExpended2 = new javax.swing.JLabel();
        TextRiskStatus = new javax.swing.JLabel();
        LabelTotalExpended1 = new javax.swing.JLabel();
        TextProjectedHrs = new javax.swing.JLabel();
        LabelTotalExpended = new javax.swing.JLabel();
        TextTotalExpended = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTotalExpended6 = new javax.swing.JLabel();
        requirementFuncBtnReset = new javax.swing.JButton();
        ComboBoxRequirementType = new ComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextRequirementDescription = new javax.swing.JTextArea();
        LabelTotalExpended10 = new javax.swing.JLabel();
        LabelTotalExpended11 = new javax.swing.JLabel();
        TextRequirementId = new javax.swing.JLabel();
        LabelTotalExpended7 = new javax.swing.JLabel();
        ComboBoxRequirementStatus = new ComboBox();
        jLabel4 = new javax.swing.JLabel();
        LabelTotalExpended12 = new javax.swing.JLabel();
        TextRequirementExpenedHours = new javax.swing.JLabel();
        requirementFuncBtnSave = new javax.swing.JButton();
        TextRequirementEstimatedHours = new javax.swing.JLabel();
        LabelTotalExpended13 = new javax.swing.JLabel();
        requirementFuncBtnUpdateExpendedHours = new javax.swing.JButton();
        requirementFuncBtnUpdateEstimatedHours = new javax.swing.JButton();

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        projectFuncBtnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnBack.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnBack.setText("Back");
        projectFuncBtnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmt_logo_smaill.jpg"))); // NOI18N
        jLabel1.setAlignmentY(1.0F);

        projectFuncBtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectFuncBtnHome.setForeground(new java.awt.Color(0, 51, 102));
        projectFuncBtnHome.setText("Home");
        projectFuncBtnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        projectFuncBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectFuncBtnHomeActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        LabelTotalExpended4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended4.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended4.setText("Proj. Id");
        LabelTotalExpended4.setToolTipText("");
        LabelTotalExpended4.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended4.setName(""); // NOI18N
        LabelTotalExpended4.setPreferredSize(new java.awt.Dimension(100, 25));

        TextProjId.setForeground(new java.awt.Color(204, 204, 204));
        TextProjId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjId.setText("0");
        TextProjId.setToolTipText("");
        TextProjId.setMinimumSize(new java.awt.Dimension(100, 25));
        TextProjId.setName(""); // NOI18N
        TextProjId.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended3.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended3.setText("Proj. Status");
        LabelTotalExpended3.setToolTipText("");
        LabelTotalExpended3.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended3.setName(""); // NOI18N
        LabelTotalExpended3.setPreferredSize(new java.awt.Dimension(100, 25));

        TextStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextStatus.setText("In-Process");
        TextStatus.setToolTipText("");
        TextStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextStatus.setName(""); // NOI18N
        TextStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended2.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended2.setText("Risks Status");
        LabelTotalExpended2.setToolTipText("");
        LabelTotalExpended2.setMinimumSize(new java.awt.Dimension(100, 25));
        LabelTotalExpended2.setName(""); // NOI18N
        LabelTotalExpended2.setPreferredSize(new java.awt.Dimension(100, 25));

        TextRiskStatus.setForeground(new java.awt.Color(204, 204, 204));
        TextRiskStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRiskStatus.setText("Risks Resolved");
        TextRiskStatus.setToolTipText("");
        TextRiskStatus.setMinimumSize(new java.awt.Dimension(100, 25));
        TextRiskStatus.setName(""); // NOI18N
        TextRiskStatus.setPreferredSize(new java.awt.Dimension(100, 25));

        LabelTotalExpended1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended1.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended1.setText("Projected Hours");
        LabelTotalExpended1.setToolTipText("");
        LabelTotalExpended1.setName(""); // NOI18N
        LabelTotalExpended1.setPreferredSize(new java.awt.Dimension(130, 25));

        TextProjectedHrs.setForeground(new java.awt.Color(204, 204, 204));
        TextProjectedHrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextProjectedHrs.setText("0");
        TextProjectedHrs.setToolTipText("");
        TextProjectedHrs.setName(""); // NOI18N
        TextProjectedHrs.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        LabelTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended.setText("Expended Hours");
        LabelTotalExpended.setToolTipText("");
        LabelTotalExpended.setName(""); // NOI18N
        LabelTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        TextTotalExpended.setForeground(new java.awt.Color(204, 204, 204));
        TextTotalExpended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTotalExpended.setText("0");
        TextTotalExpended.setToolTipText("");
        TextTotalExpended.setName(""); // NOI18N
        TextTotalExpended.setPreferredSize(new java.awt.Dimension(130, 25));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Requirement Details");
        jLabel3.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        LabelTotalExpended6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended6.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended6.setText("Req. Type:");
        LabelTotalExpended6.setToolTipText("");
        LabelTotalExpended6.setName(""); // NOI18N
        LabelTotalExpended6.setPreferredSize(new java.awt.Dimension(130, 25));

        requirementFuncBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        requirementFuncBtnReset.setForeground(new java.awt.Color(204, 0, 0));
        requirementFuncBtnReset.setText("Reset Form");
        requirementFuncBtnReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        requirementFuncBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requirementFuncBtnResetActionPerformed(evt);
            }
        });

        ComboBoxRequirementType.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxRequirementType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type...", "Functional", "Non-Functional" }));
        ComboBoxRequirementType.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxRequirementType.setPreferredSize(new java.awt.Dimension(163, 33));
        ComboBoxRequirementType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboBoxRequirementTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBoxRequirementTypeFocusLost(evt);
            }
        });

        TextRequirementDescription.setColumns(20);
        TextRequirementDescription.setRows(5);
        TextRequirementDescription.setText("Enter requirement description...");
        jScrollPane2.setViewportView(TextRequirementDescription);

        LabelTotalExpended10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended10.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended10.setText("Description:");
        LabelTotalExpended10.setToolTipText("");
        LabelTotalExpended10.setName(""); // NOI18N
        LabelTotalExpended10.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended11.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended11.setText("Req. Id:");
        LabelTotalExpended11.setToolTipText("");
        LabelTotalExpended11.setName(""); // NOI18N
        LabelTotalExpended11.setPreferredSize(new java.awt.Dimension(130, 25));

        TextRequirementId.setForeground(new java.awt.Color(51, 51, 51));
        TextRequirementId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRequirementId.setText("0");
        TextRequirementId.setToolTipText("");
        TextRequirementId.setName(""); // NOI18N
        TextRequirementId.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended7.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTotalExpended7.setText("Req. Status:");
        LabelTotalExpended7.setToolTipText("");
        LabelTotalExpended7.setName(""); // NOI18N
        LabelTotalExpended7.setPreferredSize(new java.awt.Dimension(130, 25));

        ComboBoxRequirementStatus.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 153, 153))));
        ComboBoxRequirementStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select status...", "In-process", "Complete" }));
        ComboBoxRequirementStatus.setMinimumSize(new java.awt.Dimension(163, 33));
        ComboBoxRequirementStatus.setPreferredSize(new java.awt.Dimension(163, 33));
        ComboBoxRequirementStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboBoxRequirementStatusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBoxRequirementStatusFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Edit Requirement");

        LabelTotalExpended12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended12.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended12.setText("Req. Expended Hours:");
        LabelTotalExpended12.setToolTipText("");
        LabelTotalExpended12.setName(""); // NOI18N
        LabelTotalExpended12.setPreferredSize(new java.awt.Dimension(130, 25));

        TextRequirementExpenedHours.setForeground(new java.awt.Color(51, 51, 51));
        TextRequirementExpenedHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRequirementExpenedHours.setText("0");
        TextRequirementExpenedHours.setToolTipText("");
        TextRequirementExpenedHours.setName(""); // NOI18N
        TextRequirementExpenedHours.setPreferredSize(new java.awt.Dimension(130, 25));

        requirementFuncBtnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        requirementFuncBtnSave.setForeground(new java.awt.Color(0, 51, 102));
        requirementFuncBtnSave.setText("Save");
        requirementFuncBtnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        requirementFuncBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requirementFuncBtnSaveActionPerformed(evt);
            }
        });

        TextRequirementEstimatedHours.setForeground(new java.awt.Color(51, 51, 51));
        TextRequirementEstimatedHours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextRequirementEstimatedHours.setText("0");
        TextRequirementEstimatedHours.setToolTipText("");
        TextRequirementEstimatedHours.setName(""); // NOI18N
        TextRequirementEstimatedHours.setPreferredSize(new java.awt.Dimension(130, 25));

        LabelTotalExpended13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTotalExpended13.setForeground(new java.awt.Color(51, 51, 51));
        LabelTotalExpended13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotalExpended13.setText("Req. Estimated Hours:");
        LabelTotalExpended13.setToolTipText("");
        LabelTotalExpended13.setName(""); // NOI18N
        LabelTotalExpended13.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextRequirementId, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(LabelTotalExpended11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTotalExpended12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextRequirementExpenedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTotalExpended13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextRequirementEstimatedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxRequirementType, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxRequirementStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelTotalExpended10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(requirementFuncBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(requirementFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(TextRequirementId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(TextRequirementExpenedHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(TextRequirementEstimatedHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelTotalExpended6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelTotalExpended7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(ComboBoxRequirementType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ComboBoxRequirementStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(LabelTotalExpended10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requirementFuncBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requirementFuncBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        requirementFuncBtnUpdateExpendedHours.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requirementFuncBtnUpdateExpendedHours.setForeground(new java.awt.Color(0, 51, 102));
        requirementFuncBtnUpdateExpendedHours.setText("Update Expended Hours");
        requirementFuncBtnUpdateExpendedHours.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        requirementFuncBtnUpdateExpendedHours.setMaximumSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateExpendedHours.setMinimumSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateExpendedHours.setName(""); // NOI18N
        requirementFuncBtnUpdateExpendedHours.setPreferredSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateExpendedHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requirementFuncBtnUpdateExpendedHoursActionPerformed(evt);
            }
        });

        requirementFuncBtnUpdateEstimatedHours.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requirementFuncBtnUpdateEstimatedHours.setForeground(new java.awt.Color(0, 51, 102));
        requirementFuncBtnUpdateEstimatedHours.setText("Update Estimate Hours");
        requirementFuncBtnUpdateEstimatedHours.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        requirementFuncBtnUpdateEstimatedHours.setMaximumSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateEstimatedHours.setMinimumSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateEstimatedHours.setPreferredSize(new java.awt.Dimension(280, 60));
        requirementFuncBtnUpdateEstimatedHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requirementFuncBtnUpdateEstimatedHoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextProjId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextRiskStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 6, Short.MAX_VALUE))
                                    .addComponent(TextProjectedHrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTotalExpended, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(requirementFuncBtnUpdateEstimatedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(requirementFuncBtnUpdateExpendedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectFuncBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(projectFuncBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTotalExpended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextProjectedHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelTotalExpended1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextRiskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LabelTotalExpended4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextProjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requirementFuncBtnUpdateExpendedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requirementFuncBtnUpdateEstimatedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void projectFuncBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnBackActionPerformed
        ViewProjectRequirements pr = new ViewProjectRequirements(projIdGlobal);
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_projectFuncBtnBackActionPerformed

    private void projectFuncBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectFuncBtnHomeActionPerformed
        ViewHome vh = new ViewHome();
        vh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_projectFuncBtnHomeActionPerformed

    private void requirementFuncBtnUpdateExpendedHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requirementFuncBtnUpdateExpendedHoursActionPerformed

    }//GEN-LAST:event_requirementFuncBtnUpdateExpendedHoursActionPerformed

    private void requirementFuncBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requirementFuncBtnResetActionPerformed
        ModelRequirement reqModel = dataAccess.GetRequirement(reqIdGlobal);
        TextRequirementId.setText(String.valueOf(reqIdGlobal));
        TextRequirementExpenedHours.setText(String.valueOf(dataAccess.GetRequirementExpendedHours(reqIdGlobal)));
        TextRequirementEstimatedHours.setText(String.valueOf(dataAccess.GetRequirementEstimatedHours(reqIdGlobal)));
        ComboBoxRequirementType.setSelectedItem(reqModel.reqType);
        ComboBoxRequirementStatus.setSelectedItem(reqModel.reqStatus);
        TextRequirementDescription.setText(reqModel.reqDescription);
    }//GEN-LAST:event_requirementFuncBtnResetActionPerformed

    private void ComboBoxRequirementTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRequirementTypeFocusGained

    }//GEN-LAST:event_ComboBoxRequirementTypeFocusGained

    private void ComboBoxRequirementTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRequirementTypeFocusLost

    }//GEN-LAST:event_ComboBoxRequirementTypeFocusLost

    private void ComboBoxRequirementStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRequirementStatusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRequirementStatusFocusGained

    private void ComboBoxRequirementStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxRequirementStatusFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRequirementStatusFocusLost

    private void requirementFuncBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requirementFuncBtnSaveActionPerformed
        System.out.println("Add/Update Function");
        String button1InitialState = ComboBoxRequirementType.getSelectedItem().toString();
        String button2InitialState = ComboBoxRequirementStatus.getSelectedItem().toString();
        String description = TextRequirementDescription.getText();

        if(button1InitialState.equalsIgnoreCase("Select type...") || button2InitialState.equalsIgnoreCase("Select status...") || description.equalsIgnoreCase("Enter requirement description...")){
            //do nothing maybe display error
        } else{
            //DefaultTableModel modelTeamMembersTbl = (DefaultTableModel)tableTeamMembers.getModel();
            ModelRequirement updateRequirement = new ModelRequirement();
            updateRequirement.projNumber = projIdGlobal;
            updateRequirement.reqId = reqIdGlobal;
            updateRequirement.reqDescription = TextRequirementDescription.getText();
            updateRequirement.reqType = ComboBoxRequirementType.getSelectedItem().toString();
            updateRequirement.reqStatus = ComboBoxRequirementStatus.getSelectedItem().toString();
            dataAccess.UpdateRequirement(updateRequirement); 
        }
        
    }//GEN-LAST:event_requirementFuncBtnSaveActionPerformed

    private void requirementFuncBtnUpdateEstimatedHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requirementFuncBtnUpdateEstimatedHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requirementFuncBtnUpdateEstimatedHoursActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox ComboBoxRequirementStatus;
    private ComboBox ComboBoxRequirementType;
    private javax.swing.JLabel LabelTotalExpended;
    private javax.swing.JLabel LabelTotalExpended1;
    private javax.swing.JLabel LabelTotalExpended10;
    private javax.swing.JLabel LabelTotalExpended11;
    private javax.swing.JLabel LabelTotalExpended12;
    private javax.swing.JLabel LabelTotalExpended13;
    private javax.swing.JLabel LabelTotalExpended2;
    private javax.swing.JLabel LabelTotalExpended3;
    private javax.swing.JLabel LabelTotalExpended4;
    private javax.swing.JLabel LabelTotalExpended6;
    private javax.swing.JLabel LabelTotalExpended7;
    private javax.swing.JLabel TextProjId;
    private javax.swing.JLabel TextProjectedHrs;
    private javax.swing.JTextArea TextRequirementDescription;
    private javax.swing.JLabel TextRequirementEstimatedHours;
    private javax.swing.JLabel TextRequirementExpenedHours;
    private javax.swing.JLabel TextRequirementId;
    private javax.swing.JLabel TextRiskStatus;
    private javax.swing.JLabel TextStatus;
    private javax.swing.JLabel TextTotalExpended;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton projectFuncBtnBack;
    private javax.swing.JButton projectFuncBtnHome;
    private javax.swing.JButton requirementFuncBtnReset;
    private javax.swing.JButton requirementFuncBtnSave;
    private javax.swing.JButton requirementFuncBtnUpdateEstimatedHours;
    private javax.swing.JButton requirementFuncBtnUpdateExpendedHours;
    // End of variables declaration//GEN-END:variables
}
